### ISSUE TITLE
Explaination of Mod Features

### ISSUE THREAD

**Issue by 24-7-testing** [jahirxtrap/randomisfits#1]
Hi! I downloaded and installed Random Misfits, but am having trouble figuring out how to use certain features. Would you consider adding more info to your Modrinth page? For example, a list of everything that is in your mod, what the items do, how to craft them, and how to use them would be very helpful.

**Comment by jahirxtrap** [comment]
I'll add more information about the items. For recipes I suggest using JEI, REI or EMI

**Comment by 24-7-testing** [comment]
Awesome, thanks! What's JEI, REI, or EMI? I'm not familiar with those acronyms.

**Comment by 24-7-testing** [comment]
Awesome, thanks a bunch!
