### ISSUE TITLE
Recipe Issue

### ISSUE THREAD

**Issue by Azturax** [jahirxtrap/randomisfits#2]
Hi Jahirxtrap

I have a problem of getting the crafting recipes, (in particular "handle") on neoforge 1.21.3 got REI installed
REI is not showing it. Also smithing recipes are not displayed, it shows how to repair the zurite armor but not how to craft it.

Would be so nice if you get it fixed!

**Comment by jahirxtrap** [comment]
It's a bug with REI mod: shedaniel/RoughlyEnoughItems#1760
